[package]
name = "strava-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
dotenvy = "0.15.7"
serde = "1.0.219"
tokio = "1.47.1"
url = "2.5.4"
reqwest = { version = "0.12.8", features = ["json"] }

[dev-dependencies]
